[listener]
type="socket"

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
ports=["tcp/8022", "tcp/8023"]
services=["ssh-simulator"]

[service.telnet]
type="telnet"
image="/data/screenshot-20171030174349.png"
server-name="WS-3244"

[[port]]
port="tcp/5900"
services=["telnet"]

[service.mongodb]
type="mongodb"
version="3.4.2"
#dbs=[ {Name="My_DB", SizeOnDisk="8192", Empty="false"},
#      {Name="example", SizeOnDisk="32768", Empty="false"}, ]

[[port]]
port="tcp/27017"
services=["mongodb"]


[channel.console]
type="console"

[[filter]]
channel=["console"]

[[logging]]
output = "stdout"
level = "debug"
