[listener]
type="socket"

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
ports=["tcp/8022", "tcp/8023"]
services=["ssh-simulator"]

[service.telnet]
type="telnet"
image="/data/screenshot-20171030174349.png"
server-name="WS-3244"

[[port]]
port="tcp/5900"
services=["telnet"]

[channel.console]
type="console"

[[filter]]
channel=["console"]

[[logging]]
output = "stdout"
level = "debug"
