FROM influx6/lxcontains-ubuntu

# Install gometalinter
RUN go get -u -v github.com/alecthomas/gometalinter

# Install missing lint tools
RUN gometalinter --install

RUN go get -u -v github.com/honeytrap/honeytrap

WORKDIR /go/src/github.com/honeytrap/honeytrap

# Get all dependencies to fix issue with linter on ./director
#RUN go get -v

# Run go tests
RUN go test -v ./director/...
RUN go test -v ./protocol/...
RUN go test -v ./proxies/...
RUN go test -v ./pushers/...
RUN go test -v ./server/...
RUN go test -v ./sniffer/...
RUN go test -v ./utils/...

RUN go list ./...|xargs go test -v 
RUN go list ./...|xargs go vet -v 

# Run go linters
RUN gometalinter --deadline 2m --errors --vendor ./director/...
RUN gometalinter --deadline 2m --errors --vendor ./proxies/...
RUN gometalinter --deadline 2m --errors --vendor ./pushers/...
RUN gometalinter --deadline 2m --errors --vendor ./server/...
RUN gometalinter --deadline 2m --errors --vendor ./sniffer/...
RUN gometalinter --deadline 2m --errors --vendor ./utils/...
