FROM influx6/lxcontains-ubuntu

ADD . /go/src/github.com/honeytrap/honeytrap

WORKDIR /go/src/github.com/honeytrap/honeytrap

# Install gometalinter
RUN go get -u -v github.com/alecthomas/gometalinter

# Install missing lint tools
RUN gometalinter --install

# Run go tests 
RUN go test -v ./director/...
RUN go test -v ./protocol/...
RUN go test -v ./providers/...
RUN go test -v ./proxies/...
RUN go test -v ./pushers/...
RUN go test -v ./server/...
RUN go test -v ./sniffer/...
RUN go test -v ./utils/...

# Run go linters
RUN gometalinter -v ./director/...
RUN gometalinter -v ./protocol/...
RUN gometalinter -v ./providers/...
RUN gometalinter -v ./proxies/...
RUN gometalinter -v ./pushers/...
RUN gometalinter -v ./server/...
RUN gometalinter -v ./sniffer/...
RUN gometalinter -v ./utils/...
