[cef-mappings]
[[service]]
name="ssh"
type="password-authentication"
[[service.mapping]]
ceffield="foo"
logfield="bar"
[[service.mapping]]
ceffield="bar"
logfield="foo"
[[service.static]]
ceffield="always"
logfield="on"
[[service]]
name="ftp"
type="password_auth"
[[service.mapping]]
ceffield="foofoo"
logfield="barbar"
[[service.mapping]]
ceffield="foobar"
logfield="barfoo"